# Generated by Django 3.0.3 on 2020-05-03 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20200502_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
    ]
