# Generated by Django 3.0.3 on 2020-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200315_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.CharField(default='flag2', max_length=255),
            preserve_default=False,
        ),
    ]
